# Generated by Django 4.2.7 on 2023-11-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='albums.artist')),
            ],
        ),
    ]
