# Generated by Django 4.2.7 on 2023-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
