# Generated by Django 4.2.7 on 2023-11-13 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='created_on',
        ),
        migrations.AddField(
            model_name='album',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
