# Generated by Django 4.2.7 on 2023-11-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_album_created_on_album_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createddate',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='title',
            name='album_title',
        ),
    ]
