# Generated by Django 4.2.7 on 2023-11-15 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_delete_createddate_delete_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title'),
        ),
    ]
